### ISSUE TITLE
Installation instructions and documentation

### ISSUE THREAD

**Issue by xyproto** [fccm/OCamlSDL2#10]
Hi,

OCamlSDL2 works great, thanks for creating it!

I'm using it here: https://github.com/xyproto/hello_sdl2/tree/master/ocaml

But I wonder - would it be possible to offer users simpler installation instructions for installing OCamlSDL2? There are quite a few commands that has to be executed, instead of the more common "configure && make && make install".

And, is there some sort of API documentation available?

The examples were of great help.

Thanks!

Best regards,
Alexander F Rødseth

**Comment by fccm** [comment]
The different commands for installing is the price for making it portable on linux and windows. And there is also some generated files.

The API documentation can be produced by the usual command: make doc
