### ISSUE TITLE
Support for sdlttf

### ISSUE THREAD

**Issue by smimram** [fccm/OCamlSDL2#14]
Hi,

it would be nice if support for sdlttf could be added. More precisely, we would need `Sdlttf.init`, `Sdlttf.open_font` and `Sdlttf.render_utf8_shaded`.

Thanks!

**Comment by fccm** [comment]
The OCaml interface to the SDL2_ttf library is maintained in a different repository:
https://github.com/fccm/OCamlSDL2_TTF

There are also these repositories available:
https://github.com/fccm/OCamlSDL2_Image
https://github.com/fccm/OCamlSDL2_Mixer
https://github.com/fccm/OCamlSDL2_Net

**Comment by smimram** [comment]
Ah great, I did not know about that, thanks!
