### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by sciencemanx** [fccm/OCamlSDL2#16]
Hey does this project support MacOS? ie
- tested?
- untested but might work?
- won't work?
- etc.

Thanks

**Comment by fccm** [comment]
OCamlSDL2 was very easy to compile on Windows even though I'm not an expert with Windows. SDL2 is well known to be very portable, so I would think that it's probably easy to compile on MacOS too.

You can see in the src/ directory that there are 2 possible `Makefile.config` provided, one for Linux and one for Windows that uses MinGW compiler under Cygwin:
- `Makefile.config.unix`
- `Makefile.config.win32`

If you want to contribute a `Makefile.config.macos` you are very welcome! :)

If you have difficulties to compile, but no time to explore/investigate, but if you have lots of money you can also donate me a Mac computer (someone already did, something like 10 years ago, for glMLite compatibility with MacOS, but I don't have this mac anymore).

**Comment by fccm** [comment]
In the following thread, the person with the nickname `rnt111` reports that ocamlsdl2 works well on Mac:
https://www.reddit.com/r/ocaml/comments/azbztb/ocaml_graphics_and_sound_libraries/

**Comment by csoren** [comment]
OCamlSDL2 works without changes for me on macOS 12.2 (the latest as of this writing). I think you can close this issue and add macOS as supported.
