### ISSUE TITLE
OCamlSDL2 fails to build and install (opam) on Windows, cygwin

### ISSUE THREAD

**Issue by jarmuszz** [fccm/OCamlSDL2#31]
Building on windows fails with "The system cannot find the path specified." (check the [log.txt](https://github.com/fccm/OCamlSDL2/files/8681218/log.txt) file. I translated the error message here in the issue as the original one in the logfile is in polish).

As the result, opam's CI system automatically prohibited this package from installing on win32:
`opam install ocamlsdl2`
results with
`[ERROR] ocamlsdl2 unmet availability conditions, e.g. os != "win32"`

Details:
- `ocamlc --version` : 4.11.0
- `sdl2-config --version` : 2.0.22
- `winver` : Windows Server 1809
- virtualization: vbox

This is the only spare virt machine on which I could test it on. I'd be glad if anyone would test this on other windows versions.

**Comment by fccm** [comment]
(You can set the English language with LANG=en)

Have you check what is the path for the headers?

**Comment by fccm** [comment]
In the command line that produced the error the path for headers is `/usr/include/SDL2`.
Did you check if the headers for SDL2 are there?

Header files in the C programming language are files with `*.h` file extension.
A C lib always provide header files like this. This is the equivalence of `*.mli` files of ocaml. In OCaml we call it signature files or interface files, but in C we call it header files.

In both C with **gcc** and OCaml this path is provided by `-I` as you can see in the log file you provided.

**Comment by jarmuszz** [comment]
SDL headers are present in `/usr/include/SDL2`. Moreover,
```c
#include <SDL2/SDL.h>
int
main(int argc, char *argv[])
{
        SDL_Init(SDL_INIT_VIDEO);
        SDL_Window *win = SDL_CreateWindow("foobar",
                        SDL_WINDOWPOS_UNDEFINED,
                        SDL_WINDOWPOS_UNDEFINED,
                        200, 200,
                        SDL_WINDOW_SHOWN);

        SDL_Delay(500);
        SDL_Quit();
}
```
compiles and runs fine with
`x86_64-w64-mingw32-gcc main.c -I /usr/include/ -L /usr/lib -lmingw32 -lSDL2main -lSDL2 -mwindows`

Interestingly, the `x86_64-w64-mingw32-gcc` binary doesn't seem to include nor link the "standard" directories such as `/usr/lib` and `/usr/include`.

I also noticed that the command that errors out uses the i686 gcc instead of the x86_64.

I tried to "extract" a c compiler command from the `ocamlc` line that fails to get a more in-depth error message but I was not able to reach anything worth mentioning.

Also I think it's worth to mention that it's a *windows's* error message, not a cygwin/posix one.

**Comment by fccm** [comment]
In the logs you provide, the command line was:
`ocamlc -cc "c:/cygwin/bin/i686-w64-mingw32-gcc.exe -g -Wall -Werror" -ccopt "-static -I/usr/include/SDL2 -Dmain=SDL_main -g -O " sdlinit_stub.c`
If your test in pure C does work, you can just put the same arguments.
You can replace gcc-32bits by gcc-64bit if you want.
You can see that the -cc command provides the gcc command.
You can probably remove -Wall and -Werror (kitykate already told me I should remove it from a release)
You also remove -static if this is not a static version that you want, or if the SDL2 that you installed don't include the static version.
If you want to see what is the command line run by ocamlopt and ocamlc the argument is `-verbose`.
In the ocamlc call the argument -ccopt are the arguements that will be provided to the C compiler.

If this one works:
`x86_64-w64-mingw32-gcc main.c -I /usr/include/ -L /usr/lib -lmingw32 -lSDL2main -lSDL2 -mwindows`

You could try:
`ocamlc -cc "x86_64-w64-mingw32-gcc" -ccopt "-I /usr/include/SDL2 -I /usr/include  -L /usr/lib -lmingw32 -lSDL2main -lSDL2 -mwindows -Dmain=SDL_main -g -O " sdlinit_stub.c`

**Comment by jarmuszz** [comment]
I feel kinda dumb now. I forgot that the `Makefile.config` file has to be created by hand, not generated by the main Makefile and so I was placing all of my fixes in `Makefile.config.win32` wondering why won't they work... :smiling_face_with_tear: 

The only change that has to be made to build successfully on windows is removing the `-Werror` (as you said above).

BTW thanks for all of this info, it surely will help me later :)
